### ISSUE TITLE
when building project (asp.net web api 2), it fires an error Running transformation: System.IO.FileNotFoundException: Could not load file or assembly ‘System.Web.Http, Version=4.0.0.0,

### ISSUE THREAD

**Issue by tong9977** [stevegreatrex/ProxyApi#9]
when building project (asp.net web api 2), it fires an error
Running transformation: System.IO.FileNotFoundException: Could not load file or assembly ‘System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35′ or one of its dependencies. The system cannot find the file specified.
File name: ‘System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35′
at ProxyApi.Reflection.ControllerElementsProvider.IsControllerType(Type type)
at System.Linq.Enumerable.c__DisplayClassf`1.b__e(TSource x)
at System.Linq.Enumerable.c__DisplayClassf`1.b__e(TSource x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at ProxyApi.ProxyGenerator.GenerateProxyScript()
at Microsoft.VisualStudio.TextTemplating6A51537BC8E857274E2ACC1DC9A85AF079A0BEA59FB39D6D854FEC5C83FB6C0B29B7F900AE5F91111534E20029FD9362C3BB7781F9A75BAC4FAADBECAF5C6E54.GeneratedTextTransformation.TransformText() in d:\Projects\Server\Modules\Emeint.Server\Emeint.Server.Vendors\Scripts\proxyapi.intellisense.tt:line 28

**Comment by tong9977** [comment]
https://www.scientificcomputing.com/news/2016/02/fujitsu-deep-learning-technology-analyzes-time-series-data-high-precision
